import { afterEach, describe, expect, it, vi } from 'vitest';
import { act, fireEvent, render, screen } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { MemoryRouter } from 'react-router-dom';
import { AuthContext } from '../auth/context';
import { DashboardPage } from './DashboardPage';
import { ToastProvider } from '../../components/ui/ToastProvider';
import type { TransactionListItem } from '../transactions/api';
import { jsonResponse, ok } from '../../test/mockResponse';

const monthlyFixture = {
  byCurrency: [
    {
      currency: 'ARS',
      months: [
        { month: '2026-02', income: 100000, expense: 40000 },
        { month: '2026-03', income: 120000, expense: 45000 },
        { month: '2026-04', income: 110000, expense: 30000 },
        { month: '2026-05', income: 130000, expense: 60000 },
        { month: '2026-06', income: 140000, expense: 55000 },
        { month: '2026-07', income: 250000, expense: 50000 },
      ],
    },
  ],
};

const transaction1: TransactionListItem = {
  id: 't1',
  accountId: 'acc1',
  categoryId: 'cat1',
  paymentMethodId: 'pm1',
  type: 'INCOME',
  amount: 15000,
  currency: 'ARS',
  exchangeRateAtTime: null,
  date: '2026-07-05',
  description: 'Sueldo',
  createdAt: '2026-07-05T10:00:00Z',
  recurringExpenseId: null,
  autoGenerated: false,
  sharedAmount: 0,
  shareCount: 0,
  pendingCount: 0,
  settledShareId: null,
  settledExpenseId: null,
  settledExpenseDescription: null,
};

const transaction2: TransactionListItem = {
  id: 't2',
  accountId: 'acc1',
  categoryId: null,
  paymentMethodId: null,
  type: 'EXPENSE',
  amount: 3200,
  currency: 'ARS',
  exchangeRateAtTime: null,
  date: '2026-07-06',
  description: null,
  createdAt: '2026-07-06T10:00:00Z',
  recurringExpenseId: null,
  autoGenerated: false,
  sharedAmount: 0,
  shareCount: 0,
  pendingCount: 0,
  settledShareId: null,
  settledExpenseId: null,
  settledExpenseDescription: null,
};

const pageFixture = {
  content: [transaction1, transaction2],
  page: 0,
  size: 5,
  totalElements: 2,
  totalPages: 1,
};

const ME_ONBOARDED = {
  id: 'u1',
  email: 'a@a.com',
  name: 'Ana',
  defaultCurrency: 'ARS',
  workingCurrencies: [],
  hasPassword: true,
  googleLinked: false,
  emailVerified: true,
  onboarded: true,
  createdAt: '2026-07-01T10:00:00Z',
};

function stubEndpoints(overview: unknown, monthly: unknown, page: unknown, me: unknown = ME_ONBOARDED) {
  vi.stubGlobal(
    'fetch',
    vi.fn((input: RequestInfo | URL) => {
      const url = String(input);
      if (url.includes('/summary/budgets')) return ok({ budgets: [] });
      if (url.includes('/savings')) return ok([]);
      if (url.includes('/summary/expected-income'))
        return ok({ month: 7, year: 2026, byCurrency: [], sources: [] });
      if (url.includes('/summary/overview')) return ok(overview);
      if (url.includes('/summary/monthly')) return ok(monthly);
      if (url.includes('/transactions')) return ok(page);
      // S46 (D9): el CTA del empty state depende de si el usuario ya vio la guía.
      if (url.includes('/users/me')) return ok(me);
      throw new Error('URL inesperada: ' + url);
    }),
  );
}

function renderPage() {
  const queryClient = new QueryClient({
    defaultOptions: { queries: { retry: false } },
  });
  render(
    <QueryClientProvider client={queryClient}>
      <AuthContext.Provider
        value={{ accessToken: 'test-token', status: 'authenticated', setAccessToken: () => {} }}
      >
        <ToastProvider>
          <MemoryRouter>
            <DashboardPage />
          </MemoryRouter>
        </ToastProvider>
      </AuthContext.Provider>
    </QueryClientProvider>,
  );
}

afterEach(() => {
  vi.unstubAllGlobals();
});

describe('DashboardPage', () => {
  it('muestra las 4 cards de la primera moneda con valores formateados', async () => {
    stubEndpoints(
      {
        byCurrency: [
          { currency: 'ARS', totalBalance: 200000, monthIncome: 250000, monthExpense: 50000, formalBalance: 200000, informalBalance: 0 },
        ],
      },
      monthlyFixture,
      pageFixture,
    );

    renderPage();

    const ars = await screen.findByRole('article', { name: 'Resumen ARS' });
    expect(ars).toHaveTextContent('Balance total');
    expect(ars).toHaveTextContent('$ 200.000,00');
    expect(ars).toHaveTextContent('Ingresos del mes');
    expect(ars).toHaveTextContent('$ 250.000,00');
    expect(ars).toHaveTextContent('Gastos del mes');
    expect(ars).toHaveTextContent('$ 50.000,00');
    expect(ars).toHaveTextContent('Ahorro del mes');
    expect(ars).toHaveTextContent('$ 200.000,00');
    // informalBalance 0: no hay ruido de desglose formal/informal
    expect(ars).not.toHaveTextContent('Formal');
  });

  it('con informalBalance distinto de 0 muestra el desglose formal/informal', async () => {
    stubEndpoints(
      {
        byCurrency: [
          {
            currency: 'ARS',
            totalBalance: 200000,
            monthIncome: 250000,
            monthExpense: 50000,
            formalBalance: 150000,
            informalBalance: 50000,
          },
        ],
      },
      monthlyFixture,
      pageFixture,
    );

    renderPage();

    const ars = await screen.findByRole('article', { name: 'Resumen ARS' });
    expect(ars).toHaveTextContent('Formal $ 150.000,00 · Informal $ 50.000,00');
  });

  it('con dos monedas muestra el tab USD y cambia el resumen al hacer click', async () => {
    stubEndpoints(
      {
        byCurrency: [
          { currency: 'ARS', totalBalance: 200000, monthIncome: 250000, monthExpense: 50000, formalBalance: 200000, informalBalance: 0 },
          { currency: 'USD', totalBalance: 100, monthIncome: 0, monthExpense: 0, formalBalance: 100, informalBalance: 0 },
        ],
      },
      monthlyFixture,
      pageFixture,
    );

    renderPage();

    await screen.findByRole('article', { name: 'Resumen ARS' });
    const usdTab = screen.getByRole('tab', { name: 'USD' });

    fireEvent.click(usdTab);

    expect(await screen.findByRole('article', { name: 'Resumen USD' })).toBeInTheDocument();
  });

  it('muestra empty state sin datos', async () => {
    stubEndpoints(
      { byCurrency: [] },
      { byCurrency: [] },
      { content: [], page: 0, size: 5, totalElements: 0, totalPages: 0 },
    );

    renderPage();

    // EmptyState (§5): título + mensaje en nodos separados, no una sola oración.
    expect(await screen.findByText('Todavía no hay datos')).toBeInTheDocument();
    expect(
      screen.getByText('Creá una cuenta y registrá transacciones para ver el resumen.'),
    ).toBeInTheDocument();
    // S46 (D9): ya vio la guía, así que lo que falta es una cuenta.
    expect(await screen.findByRole('button', { name: 'Nueva cuenta' })).toBeInTheDocument();
  });

  // S46 (D9) — el caso que motivó el sprint: registro con Google, dashboard vacío. Hasta acá no
  // ofrecía NADA, ni un botón.
  it('sin datos y sin haber visto la guía, el CTA es la guía', async () => {
    stubEndpoints(
      { byCurrency: [] },
      { byCurrency: [] },
      { content: [], page: 0, size: 5, totalElements: 0, totalPages: 0 },
      { ...ME_ONBOARDED, onboarded: false },
    );

    renderPage();

    expect(await screen.findByRole('button', { name: 'Empezar la guía' })).toBeInTheDocument();
    expect(screen.queryByRole('button', { name: 'Nueva cuenta' })).not.toBeInTheDocument();
  });

  it('muestra los últimos movimientos con descripción, fallback y montos formateados', async () => {
    stubEndpoints(
      {
        byCurrency: [
          { currency: 'ARS', totalBalance: 200000, monthIncome: 250000, monthExpense: 50000, formalBalance: 200000, informalBalance: 0 },
        ],
      },
      monthlyFixture,
      pageFixture,
    );

    renderPage();

    expect(await screen.findByText('Sueldo')).toBeInTheDocument();
    expect(screen.getByText('Sin descripción')).toBeInTheDocument();
    expect(screen.getByText('+$ 15.000,00')).toBeInTheDocument();
    expect(screen.getByText('−$ 3.200,00')).toBeInTheDocument();
  });

  it('muestra el heading del gráfico de ingresos vs gastos', async () => {
    stubEndpoints(
      {
        byCurrency: [
          { currency: 'ARS', totalBalance: 200000, monthIncome: 250000, monthExpense: 50000, formalBalance: 200000, informalBalance: 0 },
        ],
      },
      monthlyFixture,
      pageFixture,
    );

    renderPage();

    expect(
      await screen.findByRole('heading', { name: 'Ingresos vs gastos' }),
    ).toBeInTheDocument();
  });

  it('si falla el gráfico o los movimientos, muestra un error en vez de datos engañosos', async () => {
    const fail = () => jsonResponse(500, { error: 'INTERNAL', message: 'boom' });
    vi.stubGlobal(
      'fetch',
      vi.fn((input: RequestInfo | URL) => {
        const url = String(input);
        if (url.includes('/summary/budgets')) return ok({ budgets: [] });
        if (url.includes('/savings')) return ok([]);
        if (url.includes('/summary/expected-income'))
          return ok({ month: 7, year: 2026, byCurrency: [], sources: [] });
        // S42: los compromisos del mes resuelven vacío — sin cuotas ni recurrentes la card no se
        // monta y no agrega skeletons al conteo de carga parcial.
        if (url.includes('/summary/commitments'))
          return ok({ month: 7, year: 2026, byCurrency: [] });
        if (url.includes('/summary/overview')) {
          return ok({
            byCurrency: [
              { currency: 'ARS', totalBalance: 200000, monthIncome: 250000, monthExpense: 50000, formalBalance: 200000, informalBalance: 0 },
            ],
          });
        }
        return fail();
      }),
    );

    renderPage();

    expect(
      await screen.findByText('No pudimos cargar el gráfico. Intentá de nuevo.'),
    ).toBeInTheDocument();
    expect(
      await screen.findByText('No pudimos cargar los últimos movimientos. Intentá de nuevo.'),
    ).toBeInTheDocument();
    expect(screen.queryByText('Sin movimientos en los últimos 6 meses.')).not.toBeInTheDocument();
  });

  it('si la moneda seleccionada desaparece del resumen, cae a la primera disponible', async () => {
    const ars = { currency: 'ARS', totalBalance: 200000, monthIncome: 250000, monthExpense: 50000, formalBalance: 200000, informalBalance: 0 };
    const usd = { currency: 'USD', totalBalance: 100, monthIncome: 0, monthExpense: 0, formalBalance: 100, informalBalance: 0 };
    let overviewCalls = 0;
    vi.stubGlobal(
      'fetch',
      vi.fn((input: RequestInfo | URL) => {
        const url = String(input);
        if (url.includes('/summary/budgets')) return ok({ budgets: [] });
        if (url.includes('/savings')) return ok([]);
        if (url.includes('/summary/expected-income'))
          return ok({ month: 7, year: 2026, byCurrency: [], sources: [] });
        // S42: los compromisos del mes resuelven vacío — sin cuotas ni recurrentes la card no se
        // monta y no agrega skeletons al conteo de carga parcial.
        if (url.includes('/summary/commitments'))
          return ok({ month: 7, year: 2026, byCurrency: [] });
        if (url.includes('/users/me')) return ok(ME_ONBOARDED);
        if (url.includes('/summary/overview')) {
          overviewCalls += 1;
          // primer fetch: dos monedas; refetch: USD ya no existe
          return ok({ byCurrency: overviewCalls === 1 ? [ars, usd] : [ars] });
        }
        if (url.includes('/summary/monthly')) return ok(monthlyFixture);
        if (url.includes('/transactions')) return ok(pageFixture);
        throw new Error('URL inesperada: ' + url);
      }),
    );

    const queryClient = new QueryClient({
      defaultOptions: { queries: { retry: false } },
    });
    render(
      <QueryClientProvider client={queryClient}>
        <AuthContext.Provider
          value={{ accessToken: 'test-token', status: 'authenticated', setAccessToken: () => {} }}
        >
          <ToastProvider>
            <MemoryRouter>
              <DashboardPage />
            </MemoryRouter>
          </ToastProvider>
        </AuthContext.Provider>
      </QueryClientProvider>,
    );

    await screen.findByRole('article', { name: 'Resumen ARS' });
    fireEvent.click(screen.getByRole('tab', { name: 'USD' }));
    await screen.findByRole('article', { name: 'Resumen USD' });

    await act(async () => {
      await queryClient.invalidateQueries({ queryKey: ['summary', 'overview'] });
    });

    expect(await screen.findByRole('article', { name: 'Resumen ARS' })).toBeInTheDocument();
  });

  it('mientras carga el resumen inicial, muestra el skeleton', () => {
    vi.stubGlobal(
      'fetch',
      vi.fn(() => new Promise(() => {})),
    );

    renderPage();

    // OverviewSkeleton compone 4 skeletons de card + 1 de chart (§5: forma del contenido)
    expect(screen.getAllByRole('status', { name: 'Cargando…' }).length).toBeGreaterThan(0);
  });

  it('con overview resuelto pero gráfico y movimientos colgados, muestra ambos skeletons junto con las cards', async () => {
    vi.stubGlobal(
      'fetch',
      vi.fn((input: RequestInfo | URL) => {
        const url = String(input);
        if (url.includes('/summary/budgets')) return ok({ budgets: [] });
        if (url.includes('/savings')) return ok([]);
        if (url.includes('/summary/expected-income'))
          return ok({ month: 7, year: 2026, byCurrency: [], sources: [] });
        // S42: los compromisos del mes resuelven vacío — sin cuotas ni recurrentes la card no se
        // monta y no agrega skeletons al conteo de carga parcial.
        if (url.includes('/summary/commitments'))
          return ok({ month: 7, year: 2026, byCurrency: [] });
        if (url.includes('/summary/overview')) {
          return ok({
            byCurrency: [
              { currency: 'ARS', totalBalance: 200000, monthIncome: 250000, monthExpense: 50000, formalBalance: 200000, informalBalance: 0 },
            ],
          });
        }
        // monthly y transactions quedan colgados: la carga parcial debe verse en los skeletons
        return new Promise(() => {});
      }),
    );

    renderPage();

    expect(await screen.findByRole('article', { name: 'Resumen ARS' })).toBeInTheDocument();
    // Un Skeleton (role=status, "Cargando…") para el gráfico y otro para los movimientos —
    // ExpectedIncomeCard/BudgetSection ya resolvieron ({budgets: []}, sin fuentes), así que
    // sólo quedan estos dos pendientes.
    expect(screen.getAllByRole('status', { name: 'Cargando…' })).toHaveLength(2);
  });
});
