import { afterEach, describe, expect, it, vi } from 'vitest';
import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { MemoryRouter } from 'react-router-dom';
import { AuthContext } from '../auth/context';
import { ToastProvider } from '../../components/ui/ToastProvider';
import { ReviewInbox } from './ReviewInbox';

// S38 — la bandeja de "por revisar". Lo que se fija acá es la regla que la hace útil: editar ES
// revisar, así que la fila sale sola y le deja lugar a las otras.

const CATEGORIES = [
  { id: 'cat-1', name: 'Supermercado', type: 'EXPENSE' },
  { id: 'cat-2', name: 'Sueldo', type: 'INCOME' },
];

const ACCOUNTS = [{ id: 'acc-1', name: 'Mercado Pago', type: 'WALLET', currency: 'ARS', balance: 0 }];

const METHODS = [{ id: 'pm-1', name: 'Transferencia', accountId: 'acc-1', type: 'TRANSFER' }];

function row(overrides: Record<string, unknown> = {}) {
  return {
    id: 'tx-1',
    accountId: 'acc-1',
    categoryId: null,
    paymentMethodId: null,
    type: 'EXPENSE',
    amount: 12800,
    currency: 'ARS',
    exchangeRateAtTime: null,
    date: '2026-08-01',
    description: 'MERPAGO*SUPERDIA',
    createdAt: '2026-08-01T10:00:00',
    recurringExpenseId: null,
    autoGenerated: false,
    sharedAmount: 0,
    shareCount: 0,
    pendingCount: 0,
    settledShareId: null,
    settledExpenseId: null,
    settledExpenseDescription: null,
    origin: 'IMPORT',
    pendingReview: true,
    ...overrides,
  };
}

const calls: { url: string; method: string; body: unknown }[] = [];

function stubFetch(rows: unknown[]) {
  calls.length = 0;
  vi.stubGlobal(
    'fetch',
    vi.fn((url: string, init?: RequestInit) => {
      calls.push({
        url,
        method: init?.method ?? 'GET',
        body: init?.body ? JSON.parse(init.body as string) : null,
      });
      const json = (data: unknown) =>
        Promise.resolve(
          new Response(JSON.stringify(data), {
            status: 200,
            headers: { 'Content-Type': 'application/json' },
          }),
        );
      if (url.includes('/categories')) return json(CATEGORIES);
      if (url.includes('/accounts')) return json(ACCOUNTS);
      if (url.includes('/payment-methods')) return json(METHODS);
      if (url.includes('/transactions/')) return json({});
      if (url.includes('/transactions'))
        return json({ content: rows, page: 0, size: 100, totalElements: rows.length, totalPages: 1 });
      return json([]);
    }),
  );
}

afterEach(() => vi.unstubAllGlobals());

function renderInbox(rows: unknown[]) {
  stubFetch(rows);
  const queryClient = new QueryClient({ defaultOptions: { queries: { retry: false } } });
  render(
    <QueryClientProvider client={queryClient}>
      <AuthContext.Provider
        value={{ accessToken: 't', status: 'authenticated', setAccessToken: () => {} }}
      >
        <ToastProvider>
          <MemoryRouter>
            <ReviewInbox />
          </MemoryRouter>
        </ToastProvider>
      </AuthContext.Provider>
    </QueryClientProvider>,
  );
}

describe('ReviewInbox', () => {
  it('muestra lo que entró solo, con de dónde vino', async () => {
    renderInbox([row()]);

    expect(await screen.findByDisplayValue('MERPAGO*SUPERDIA')).toBeInTheDocument();
    expect(screen.getByText('del archivo')).toBeInTheDocument();
  });

  it('vacía dice qué va a aparecer ahí, no sólo que está vacía', async () => {
    renderInbox([]);

    expect(await screen.findByText('No hay nada para revisar')).toBeInTheDocument();
    expect(screen.getByText(/lo que anotás por Telegram/)).toBeInTheDocument();
  });

  it('poner una categoría la guarda con un PATCH (y del lado del server eso la saca)', async () => {
    renderInbox([row()]);
    await screen.findByDisplayValue('MERPAGO*SUPERDIA');

    fireEvent.change(screen.getByLabelText('Categoría de MERPAGO*SUPERDIA'), {
      target: { value: 'cat-1' },
    });

    await waitFor(() => {
      const patch = calls.find((c) => c.method === 'PATCH');
      expect(patch).toBeDefined();
      expect(patch!.url).toContain('/transactions/tx-1');
      expect(patch!.body).toEqual({ categoryId: 'cat-1' });
    });
  });

  it('la descripción se guarda al salir del campo, no en cada tecla', async () => {
    renderInbox([row()]);
    const input = await screen.findByDisplayValue('MERPAGO*SUPERDIA');

    fireEvent.change(input, { target: { value: 'Supermercado del barrio' } });
    expect(calls.some((c) => c.method === 'PATCH')).toBe(false);

    fireEvent.blur(input);
    await waitFor(() => {
      const patch = calls.find((c) => c.method === 'PATCH');
      expect(patch!.body).toEqual({ description: 'Supermercado del barrio' });
    });
  });

  it('salir del campo sin haber cambiado nada no dispara ningún PATCH', async () => {
    renderInbox([row()]);
    const input = await screen.findByDisplayValue('MERPAGO*SUPERDIA');

    fireEvent.blur(input);
    expect(calls.some((c) => c.method === 'PATCH')).toBe(false);
  });

  it('"Está bien" la saca sin editarla', async () => {
    renderInbox([row()]);
    await screen.findByDisplayValue('MERPAGO*SUPERDIA');

    fireEvent.click(screen.getByRole('button', { name: 'Está bien' }));

    await waitFor(() => {
      const post = calls.find((c) => c.url.includes('/review') && c.method === 'POST');
      expect(post!.url).toContain('/transactions/tx-1/review');
    });
  });

  it('"Están todos bien" vacía la lista de una', async () => {
    renderInbox([row(), row({ id: 'tx-2', description: 'Pago SUBE' })]);
    await screen.findByDisplayValue('Pago SUBE');

    fireEvent.click(screen.getByRole('button', { name: 'Están todos bien (2)' }));

    await waitFor(() => {
      const post = calls.find((c) => c.url.endsWith('/transactions/review'));
      expect(post!.body).toEqual({ ids: ['tx-1', 'tx-2'] });
    });
  });

  it('las categorías ofrecidas son las del tipo de la fila', async () => {
    renderInbox([row()]);
    const select = (await screen.findByLabelText(
      'Categoría de MERPAGO*SUPERDIA',
    )) as HTMLSelectElement;

    const labels = Array.from(select.options).map((o) => o.textContent);
    expect(labels).toContain('Supermercado');
    // "Sueldo" es de ingreso: ofrecerla para un gasto termina en un 400 al guardar.
    expect(labels).not.toContain('Sueldo');
  });
});
