import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { render, screen, waitFor } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { AuthContext } from '../auth/context';
import { ToastProvider } from '../../components/ui/ToastProvider';
import { TransactionForm } from './TransactionForm';
import { jsonResponse } from '../../test/mockResponse';
import { selectOption, selectValue } from '../../test/selectOption';
import type { TransactionListItem } from './api';

/**
 * S50 (D2): al elegir una cuenta, el método arranca en el PREDETERMINADO de esa cuenta.
 *
 * El prefill vive en el `onChange` del selector de cuenta y NO en un `useEffect`: un efecto que
 * dependa de `accounts` vuelve a correr con cada refetch en background de react-query (foco de
 * ventana) y le pone de nuevo el método que el usuario acababa de sacar a mano. Hay un test acá
 * abajo que fija justamente eso.
 */

const santander = {
  id: 'acc-1',
  name: 'Santander',
  type: 'BANK',
  currency: 'ARS',
  balance: 1000,
  isInformal: false,
  statementCloseDay: null,
  paymentDueDay: null,
  balances: [{ currency: 'ARS', balance: 1000 }],
  createdAt: '2026-07-01T00:00:00',
  defaultPaymentMethodId: 'pm-1',
  defaultCardAccountId: null,
};

// Cuenta cuyo predeterminado es una TARJETA VINCULADA: elegirla rutea la tx a la tarjeta.
const galicia = {
  ...santander,
  id: 'acc-2',
  name: 'Galicia',
  defaultPaymentMethodId: null,
  defaultCardAccountId: 'card-1',
};

// La tarjeta, en dólares: el prefill tiene que dejar la moneda de LA TARJETA, no la de la madre.
const visaCard = {
  ...santander,
  id: 'card-1',
  name: 'Visa Galicia',
  type: 'CREDIT',
  currency: 'USD',
  balance: -100,
  balances: [{ currency: 'USD', balance: -100 }],
  linkedAccountId: 'acc-2',
  defaultPaymentMethodId: null,
  defaultCardAccountId: null,
};

const sinDefault = {
  ...santander,
  id: 'acc-3',
  name: 'Efectivo',
  type: 'CASH',
  defaultPaymentMethodId: null,
  defaultCardAccountId: null,
};

const methods = [
  { id: 'pm-1', userId: 'u', accountId: 'acc-1', name: 'Transferencia bancaria', type: 'TRANSFER', isDefault: true, createdAt: '2026-07-01T00:00:00' },
  { id: 'pm-2', userId: 'u', accountId: 'acc-1', name: 'Débito', type: 'DEBIT', isDefault: false, createdAt: '2026-07-01T00:00:00' },
  { id: 'pm-3', userId: 'u', accountId: 'acc-3', name: 'Plata en mano', type: 'CASH', isDefault: false, createdAt: '2026-07-01T00:00:00' },
];

const editTx: TransactionListItem = {
  id: 'tx-1',
  accountId: 'acc-1',
  categoryId: null,
  paymentMethodId: null,
  type: 'EXPENSE',
  amount: 100,
  currency: 'ARS',
  exchangeRateAtTime: null,
  date: '2026-07-01',
  description: 'Super',
  createdAt: '2026-07-01T00:00:00',
  recurringExpenseId: null,
  autoGenerated: false,
  sharedAmount: 0,
  shareCount: 0,
  pendingCount: 0,
  settledShareId: null,
  settledExpenseId: null,
  settledExpenseDescription: null,
};

let accountsCalls = 0;

beforeEach(() => {
  accountsCalls = 0;
  vi.stubGlobal(
    'fetch',
    vi.fn((url: string) => {
      if (url.includes('/accounts')) {
        accountsCalls += 1;
        return jsonResponse(200, [santander, galicia, visaCard, sinDefault]);
      }
      if (url.includes('/payment-methods')) {
        const accountId = new URL(url, 'http://x').searchParams.get('accountId');
        return jsonResponse(200, methods.filter((m) => !accountId || m.accountId === accountId));
      }
      return jsonResponse(200, []);
    }),
  );
});

afterEach(() => {
  vi.unstubAllGlobals();
});

function renderForm(transaction?: TransactionListItem) {
  const queryClient = new QueryClient({
    defaultOptions: { queries: { retry: false }, mutations: { retry: false } },
  });
  render(
    <QueryClientProvider client={queryClient}>
      <AuthContext.Provider
        value={{ accessToken: 't', status: 'authenticated', setAccessToken: () => {} }}
      >
        <ToastProvider>
          <TransactionForm transaction={transaction} onClose={() => {}} />
        </ToastProvider>
      </AuthContext.Provider>
    </QueryClientProvider>,
  );
  return queryClient;
}

// El Select de la casa es un listbox custom, no un <select> nativo: el valor vive en el
// data-value del trigger y se cambia clickeando la opcion. De ahi los helpers.
function method() {
  return selectValue('Método de pago', { exact: false });
}

function currency() {
  return selectValue('Moneda', { exact: false });
}

describe('TransactionForm · método predeterminado (S50)', () => {
  it('al elegir la cuenta, el método arranca en su predeterminado', async () => {
    renderForm();
    await selectOption('Cuenta', 'acc-1', { exact: false });

    await waitFor(() => expect(method()).toBe('pm-1'));
  });

  it('el usuario lo puede sacar y queda sin método', async () => {
    renderForm();
    await selectOption('Cuenta', 'acc-1', { exact: false });
    await waitFor(() => expect(method()).toBe('pm-1'));

    await selectOption('Método de pago', '', { exact: false });

    expect(method()).toBe('');
  });

  // El test que justifica que el prefill NO sea un useEffect sobre `accounts`.
  it('sacado a mano, un refetch de cuentas NO se lo vuelve a poner', async () => {
    const queryClient = renderForm();
    await selectOption('Cuenta', 'acc-1', { exact: false });
    await waitFor(() => expect(method()).toBe('pm-1'));
    await selectOption('Método de pago', '', { exact: false });

    // Lo que hace react-query al volver el foco a la ventana.
    await queryClient.refetchQueries({ queryKey: ['accounts'] });
    await waitFor(() => expect(accountsCalls).toBeGreaterThan(1));

    expect(method()).toBe('');
  });

  it('cambiar de cuenta reencuadra el método al predeterminado de la nueva', async () => {
    renderForm();
    await selectOption('Cuenta', 'acc-1', { exact: false });
    await waitFor(() => expect(method()).toBe('pm-1'));

    await selectOption('Cuenta', 'acc-3', { exact: false });

    // Efectivo no tiene predeterminado: vuelve a vacío, no se arrastra el de la anterior.
    await waitFor(() => expect(method()).toBe(''));
  });

  it('si el predeterminado es una tarjeta vinculada, la elige y deja la moneda DE LA TARJETA', async () => {
    renderForm();
    await selectOption('Cuenta', 'acc-2', { exact: false });

    // T3: la tx queda ruteada a la tarjeta, así que la moneda es la de la tarjeta (USD) y no la
    // de la cuenta madre (ARS). Es el bug que S27 ya pagó una vez, visto del otro lado.
    await waitFor(() => expect(method()).toBe('card:card-1'));
    expect(currency()).toBe('USD');
  });

  // T4: una tx vieja sin método lo tiene sin método a propósito (o la anotó el bot antes de S50).
  it('al abrir en edición no prefillea nada', async () => {
    renderForm(editTx);

    await waitFor(() => expect(screen.getByDisplayValue('Super')).toBeInTheDocument());
    expect(method()).toBe('');
  });
});
