import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { render, screen } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { MemoryRouter } from 'react-router-dom';
import { AuthContext } from '../auth/context';
import { TransactionsPage } from './TransactionsPage';
import { ToastProvider } from '../../components/ui/ToastProvider';
import { jsonResponse } from '../../test/mockResponse';

// S34: deep-link del centro de notificaciones. El tap en un movimiento del bot cae en
// /transactions?edit=<txId> y tiene que abrir el editor de ESA transacción (D3).

const emptyPage = { content: [], page: 0, size: 20, totalElements: 0, totalPages: 0 };

const accounts = [
  { id: 'a1', name: 'Efectivo', type: 'CASH', currency: 'ARS', balance: 1500, isInformal: false,
    statementCloseDay: null, paymentDueDay: null, balances: [{ currency: 'ARS', balance: 1500 }],
    createdAt: '2026-07-01T00:00:00', institution: null, linkedAccountId: null },
];

const categories = [
  { id: 'c2', userId: null, name: 'Comida', type: 'EXPENSE', color: null, icon: null,
    sourceDefaultCategoryId: null, createdAt: '2026-07-01T00:00:00' },
];

const tx = {
  id: 'tx-1',
  accountId: 'a1',
  categoryId: 'c2',
  paymentMethodId: null,
  type: 'EXPENSE',
  amount: 20000,
  currency: 'ARS',
  exchangeRateAtTime: null,
  date: '2026-07-30',
  description: 'nafta',
  createdAt: '2026-07-30T10:00:00',
  recurringExpenseId: null,
  autoGenerated: false,
  sharedAmount: 0,
  settledShareId: null,
  transferId: null,
  settledCount: 0,
};

const txPage = { content: [tx], page: 0, size: 20, totalElements: 1, totalPages: 1 };

beforeEach(() => {
  vi.stubGlobal(
    'fetch',
    vi.fn((url: string) => {
      if (url.includes('/transfers')) return jsonResponse(200, emptyPage);
      if (url.includes('/transactions')) return jsonResponse(200, txPage);
      if (url.includes('/categories')) return jsonResponse(200, categories);
      if (url.includes('/accounts')) return jsonResponse(200, accounts);
      return jsonResponse(200, []);
    }),
  );
});

afterEach(() => vi.unstubAllGlobals());

function renderPage(url: string) {
  const queryClient = new QueryClient({ defaultOptions: { queries: { retry: false } } });
  render(
    <QueryClientProvider client={queryClient}>
      <AuthContext.Provider
        value={{ accessToken: 'test-token', status: 'authenticated', setAccessToken: () => {} }}
      >
        <ToastProvider>
          <MemoryRouter initialEntries={[url]}>
            <TransactionsPage />
          </MemoryRouter>
        </ToastProvider>
      </AuthContext.Provider>
    </QueryClientProvider>,
  );
}

describe('TransactionsPage — deep-link ?edit= (S34)', () => {
  it('abre el editor de la transacción del link', async () => {
    renderPage('/transactions?edit=tx-1');

    // El rótulo aparece en el encabezado del form y en su botón de guardar.
    expect(await screen.findAllByText('Editar transacción')).not.toHaveLength(0);
    expect(await screen.findByDisplayValue('nafta')).toBeInTheDocument();
  });

  it('sin el param no abre nada', async () => {
    renderPage('/transactions');

    expect(await screen.findByRole('button', { name: 'Nuevo movimiento' })).toBeInTheDocument();
    expect(screen.queryByText('Editar transacción')).toBeNull();
  });

  it('si la transacción no está en el feed avisa en vez de quedarse mudo', async () => {
    renderPage('/transactions?edit=tx-que-no-esta');

    expect(
      await screen.findByText('No encontré ese movimiento en el feed. Buscalo con los filtros.'),
    ).toBeInTheDocument();
  });
});
