import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { MemoryRouter, useLocation } from 'react-router-dom';
import { AuthContext } from '../auth/context';
import { ToastProvider } from '../../components/ui/ToastProvider';
import { NotificationBell } from '../notifications/NotificationBell';
import { TransactionsPage } from './TransactionsPage';
import { jsonResponse } from '../../test/mockResponse';
import type { NotificationItem, NotificationsResponse } from '../notifications/api';

// El bug de verdad: con Transacciones YA abierta, el tap en una notificación cambiaba la URL y
// no pasaba nada. Los deep-links se leían con `useState(() => searchParams.get(...))`, que sólo
// corre al montar, y estando parado en la página destino no se monta nada.
//
// Por eso este archivo monta la campanita y la página JUNTAS, como en la app: el click sale del
// panel real y la página tiene que reaccionar sin remontarse.

const emptyPage = { content: [], page: 0, size: 20, totalElements: 0, totalPages: 0 };

const accounts = [
  { id: 'a1', name: 'Efectivo', type: 'CASH', currency: 'ARS', balance: 1500, isInformal: false,
    statementCloseDay: null, paymentDueDay: null, balances: [{ currency: 'ARS', balance: 1500 }],
    createdAt: '2026-07-01T00:00:00', institution: null, linkedAccountId: null },
];

const categories = [
  { id: 'c2', userId: null, name: 'Comida', type: 'EXPENSE', color: null, icon: null,
    sourceDefaultCategoryId: null, createdAt: '2026-07-01T00:00:00' },
];

function tx(overrides: Record<string, unknown> = {}) {
  return {
    id: 'tx-1',
    accountId: 'a1',
    categoryId: 'c2',
    paymentMethodId: null,
    type: 'EXPENSE',
    amount: 20000,
    currency: 'ARS',
    exchangeRateAtTime: null,
    date: '2026-07-30',
    description: 'nafta',
    createdAt: '2026-07-30T10:00:00',
    recurringExpenseId: null,
    autoGenerated: false,
    sharedAmount: 0,
    settledShareId: null,
    transferId: null,
    settledCount: 0,
    ...overrides,
  };
}

function notification(overrides: Partial<NotificationItem> = {}): NotificationItem {
  return {
    id: 'n1',
    type: 'BOT_MOVEMENT',
    title: 'Thoth anotó $20.000 en nafta',
    body: 'Efectivo · Transporte',
    targetType: 'TRANSACTION',
    targetId: 'tx-1',
    createdAt: '2026-07-30T10:00:00',
    read: false,
    ...overrides,
  };
}

function notificationsPayload(items: NotificationItem[]): NotificationsResponse {
  const movements = items.filter((i) => i.type === 'BOT_MOVEMENT');
  const alerts = items.filter((i) => i.type !== 'BOT_MOVEMENT');
  return {
    unreadCount: items.filter((i) => !i.read).length,
    accumulationDays: 3,
    movements: { recent: movements, older: [], unreadCount: movements.length },
    alerts: { recent: alerts, older: [], unreadCount: alerts.length },
  };
}

// El feed trae la transacción del bot; la bandeja, uno pendiente para que exista la tab.
function mockFetch(options: { items: NotificationItem[]; pendingReview?: boolean }) {
  const feed = { content: [tx()], page: 0, size: 20, totalElements: 1, totalPages: 1 };
  const pending = tx({ id: 'tx-9', description: 'Pago con QR Super' });

  vi.stubGlobal(
    'fetch',
    vi.fn((url: string) => {
      if (url.includes('/notifications')) {
        return jsonResponse(200, notificationsPayload(options.items));
      }
      if (url.includes('pendingReview=true')) {
        return jsonResponse(
          200,
          options.pendingReview
            ? { content: [pending], page: 0, size: 100, totalElements: 1, totalPages: 1 }
            : emptyPage,
        );
      }
      if (url.includes('/transfers')) return jsonResponse(200, emptyPage);
      if (url.includes('/transactions')) return jsonResponse(200, feed);
      if (url.includes('/categories')) return jsonResponse(200, categories);
      if (url.includes('/accounts')) return jsonResponse(200, accounts);
      return jsonResponse(200, []);
    }),
  );
}

function LocationProbe() {
  const location = useLocation();
  return <span data-testid="location">{location.pathname + location.search}</span>;
}

// Campanita + página, las dos montadas sobre /transactions: el escenario donde fallaba.
function renderStandingOnTransactions() {
  const queryClient = new QueryClient({
    defaultOptions: { queries: { retry: false }, mutations: { retry: false } },
  });
  render(
    <QueryClientProvider client={queryClient}>
      <AuthContext.Provider
        value={{ accessToken: 'test-token', status: 'authenticated', setAccessToken: () => {} }}
      >
        <ToastProvider>
          <MemoryRouter initialEntries={['/transactions']}>
            <NotificationBell />
            <TransactionsPage />
            <LocationProbe />
          </MemoryRouter>
        </ToastProvider>
      </AuthContext.Provider>
    </QueryClientProvider>,
  );
}

async function openNotification(title: string) {
  fireEvent.click(await screen.findByRole('button', { name: /Notificaciones/ }));
  fireEvent.click(await screen.findByText(title));
}

afterEach(() => vi.unstubAllGlobals());

describe('Deep-links del centro de notificaciones con Transacciones YA abierta', () => {
  beforeEach(() => mockFetch({ items: [notification()] }));

  it('el tap en el movimiento del bot abre el editor sin remontar la página', async () => {
    renderStandingOnTransactions();
    // La página ya está montada y quieta antes del click.
    expect(await screen.findByRole('button', { name: 'Nuevo movimiento' })).toBeInTheDocument();

    await openNotification('Thoth anotó $20.000 en nafta');

    expect(await screen.findByDisplayValue('nafta')).toBeInTheDocument();
    expect(await screen.findAllByText('Editar transacción')).not.toHaveLength(0);
  });

  it('deja la URL limpia, así el mismo tap vuelve a abrirlo una segunda vez', async () => {
    renderStandingOnTransactions();
    expect(await screen.findByRole('button', { name: 'Nuevo movimiento' })).toBeInTheDocument();

    await openNotification('Thoth anotó $20.000 en nafta');
    expect(await screen.findByDisplayValue('nafta')).toBeInTheDocument();

    // Consumida la orden, el param no queda pegado: es lo que permite detectar el próximo tap.
    await waitFor(() =>
      expect(screen.getByTestId('location')).toHaveTextContent('/transactions'),
    );
    expect(screen.getByTestId('location').textContent).not.toContain('edit=');

    // Se cierra el editor y se vuelve a tocar LA MISMA notificación.
    fireEvent.click(screen.getByRole('button', { name: 'Cancelar' }));
    await waitFor(() => expect(screen.queryByDisplayValue('nafta')).toBeNull());

    await openNotification('Thoth anotó $20.000 en nafta');

    expect(await screen.findByDisplayValue('nafta')).toBeInTheDocument();
  });
});

describe('Deep-link ?review=1 con Transacciones YA abierta', () => {
  beforeEach(() =>
    mockFetch({
      items: [
        notification({
          id: 'n2',
          type: 'REVIEW_INBOX',
          title: 'Thoth leyó tu resumen',
          targetType: 'REVIEW_INBOX',
          targetId: 'batch-1',
        }),
      ],
      pendingReview: true,
    }),
  );

  it('el tap en la alerta abre la bandeja estando parado en el feed', async () => {
    renderStandingOnTransactions();
    expect(await screen.findByRole('button', { name: 'Movimientos' }))
      .toHaveAttribute('aria-current', 'page');

    await openNotification('Thoth leyó tu resumen');

    expect(await screen.findByRole('button', { name: 'Por revisar (1)' }))
      .toHaveAttribute('aria-current', 'page');
  });
});
