import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { AuthContext } from '../auth/context';
import { TransactionForm } from './TransactionForm';
import { ToastProvider } from '../../components/ui/ToastProvider';
import type { TransactionListItem } from './api';
import { jsonResponse } from '../../test/mockResponse';
import { openSelect, selectOption, selectValue } from '../../test/selectOption';

const account = {
  id: 'acc-1',
  name: 'Efectivo',
  type: 'CASH',
  currency: 'ARS',
  balance: 1000,
  isInformal: false,
  statementCloseDay: null,
  paymentDueDay: null,
  balances: [{ currency: 'ARS', balance: 1000 }],
  createdAt: '2026-07-01T00:00:00',
};

const creditAccount = {
  id: 'acc-2',
  name: 'Visa',
  type: 'CREDIT',
  currency: 'ARS',
  balance: -100,
  isInformal: false,
  statementCloseDay: 10,
  paymentDueDay: 20,
  balances: [{ currency: 'ARS', balance: -100 }],
  createdAt: '2026-07-01T00:00:00',
};

const editTx: TransactionListItem = {
  id: 'tx-1',
  accountId: 'acc-1',
  categoryId: null,
  paymentMethodId: null,
  type: 'EXPENSE',
  amount: 100,
  currency: 'ARS',
  exchangeRateAtTime: null,
  date: '2026-07-01',
  description: 'Super',
  createdAt: '2026-07-01T00:00:00',
  recurringExpenseId: null,
  autoGenerated: false,
  sharedAmount: 0,
  shareCount: 0,
  pendingCount: 0,
  settledShareId: null,
  settledExpenseId: null,
  settledExpenseDescription: null,
};

let patchCalls: { url: string; body: Record<string, unknown> }[];
let patchResponse: { status: number; body: unknown };
let postCalls: { url: string; body: Record<string, unknown> }[];

beforeEach(() => {
  patchCalls = [];
  postCalls = [];
  patchResponse = { status: 200, body: { ...editTx, accountBalance: 900 } };
  vi.stubGlobal(
    'fetch',
    vi.fn((url: string, options?: RequestInit) => {
      if (options?.method === 'PATCH') {
        patchCalls.push({ url, body: JSON.parse(options.body as string) });
        return jsonResponse(patchResponse.status, patchResponse.body);
      }
      if (options?.method === 'POST') {
        const body = JSON.parse(options.body as string);
        postCalls.push({ url, body });
        return jsonResponse(201, { ...editTx, ...body, id: 'tx-new', accountBalance: 1100 });
      }
      if (url.includes('/accounts')) return jsonResponse(200, [account, creditAccount]);
      return jsonResponse(200, []);
    }),
  );
});

afterEach(() => {
  vi.unstubAllGlobals();
});

function renderEditForm() {
  const onClose = vi.fn();
  const queryClient = new QueryClient({
    defaultOptions: { queries: { retry: false }, mutations: { retry: false } },
  });
  render(
    <QueryClientProvider client={queryClient}>
      <AuthContext.Provider
        value={{ accessToken: 'test-token', status: 'authenticated', setAccessToken: () => {} }}
      >
        <ToastProvider>
          <TransactionForm transaction={editTx} onClose={onClose} />
        </ToastProvider>
      </AuthContext.Provider>
    </QueryClientProvider>,
  );
  return onClose;
}

describe('TransactionForm en edición', () => {
  it('manda solo los campos modificados en el PATCH (diff-PATCH, 7-3)', async () => {
    const onClose = renderEditForm();

    fireEvent.change(screen.getByLabelText(/Monto/), { target: { value: '150' } });
    fireEvent.click(screen.getByRole('button', { name: 'Guardar' }));

    await waitFor(() => expect(patchCalls).toHaveLength(1));
    expect(patchCalls[0].url).toContain('/transactions/tx-1');
    expect(patchCalls[0].body).toEqual({ amount: 150 });
    await waitFor(() => expect(onClose).toHaveBeenCalled());
  });

  it('sin cambios: no hace ningún request y cierra el formulario', async () => {
    const onClose = renderEditForm();

    fireEvent.click(screen.getByRole('button', { name: 'Guardar' }));

    await waitFor(() => expect(onClose).toHaveBeenCalled());
    expect(patchCalls).toHaveLength(0);
  });

  it('422 INSUFFICIENT_BALANCE: muestra mensaje claro y no cierra', async () => {
    patchResponse = {
      status: 422,
      body: { error: 'INSUFFICIENT_BALANCE', message: 'Insufficient balance' },
    };
    const onClose = renderEditForm();

    fireEvent.change(screen.getByLabelText(/Monto/), { target: { value: '99999' } });
    fireEvent.click(screen.getByRole('button', { name: 'Guardar' }));

    expect(await screen.findByRole('alert')).toHaveTextContent(
      'Saldo insuficiente en la cuenta para este gasto.',
    );
    expect(onClose).not.toHaveBeenCalled();
  });

  it('vaciar la descripción no la manda en el PATCH (limitación 7-4 documentada)', async () => {
    const onClose = renderEditForm();

    fireEvent.change(screen.getByLabelText('Descripción'), { target: { value: '' } });
    fireEvent.change(screen.getByLabelText(/Monto/), { target: { value: '150' } });
    fireEvent.click(screen.getByRole('button', { name: 'Guardar' }));

    await waitFor(() => expect(patchCalls).toHaveLength(1));
    expect(patchCalls[0].body).toEqual({ amount: 150 });
    await waitFor(() => expect(onClose).toHaveBeenCalled());
  });
});

// Sprint 22: selector de moneda discreto en alta.
describe('TransactionForm en alta (Sprint 22, moneda)', () => {
  function renderCreateForm() {
    const onClose = vi.fn();
    const queryClient = new QueryClient({
      defaultOptions: { queries: { retry: false }, mutations: { retry: false } },
    });
    render(
      <QueryClientProvider client={queryClient}>
        <AuthContext.Provider
          value={{ accessToken: 'test-token', status: 'authenticated', setAccessToken: () => {} }}
        >
          <ToastProvider>
            <TransactionForm onClose={onClose} lockedType="INCOME" />
          </ToastProvider>
        </AuthContext.Provider>
      </QueryClientProvider>,
    );
    return onClose;
  }

  it('cuenta no-CREDIT: muestra el selector con la principal por defecto y manda esa moneda', async () => {
    renderCreateForm();

    // selectOption espera a que las cuentas carguen y la opción exista
    await selectOption('Cuenta', 'acc-1', { exact: false });
    await waitFor(() => expect(selectValue('Moneda', { exact: false })).toBe('ARS')); // principal por defecto

    fireEvent.change(screen.getByLabelText(/Monto/), { target: { value: '500' } });
    fireEvent.click(screen.getByRole('button', { name: 'Guardar' }));

    await waitFor(() => expect(postCalls).toHaveLength(1));
    expect(postCalls[0].body).toMatchObject({ accountId: 'acc-1', currency: 'ARS', amount: 500 });
  });

  // Sprint 27: esto ANTES era un chip fijo deshabilitado (S23 D8, el espejo en la UI del guard
  // mono-moneda de S22 D2). Con el guard levantado, el backend acepta una compra en dólares
  // sobre una tarjeta en pesos — pero mientras el chip siguiera acá no había forma de CARGARLA
  // desde la app, que es el punto entero del sprint.
  it('cuenta CREDIT: la moneda es un selector editable, con "Otra…" para una moneda nueva', async () => {
    renderCreateForm();

    await selectOption('Cuenta', 'acc-2', { exact: false });

    await waitFor(() => expect(selectValue('Moneda', { exact: false })).toBe('ARS')); // principal
    await selectOption('Moneda', '__other__', { exact: false });
    fireEvent.change(await screen.findByLabelText('Moneda (3 letras)', { exact: false }), {
      target: { value: 'usd' },
    });
    fireEvent.change(screen.getByLabelText(/Monto/), { target: { value: '100' } });
    fireEvent.click(screen.getByRole('button', { name: 'Guardar' }));

    await waitFor(() => expect(postCalls).toHaveLength(1));
    expect(postCalls[0].body).toMatchObject({ accountId: 'acc-2', currency: 'USD', amount: 100 });
  });

  // REGRESIÓN (S27): el campo Moneda está ARRIBA del de Método de pago. Al soltar el candado
  // mono-moneda se agregó un reset de la moneda en el onChange del método —para reencuadrarla
  // cuando la tarjeta RUTEA la tx a otra cuenta— y ese reset corría siempre: elegías dólares,
  // elegías el método y te los volvía a pesos en silencio. Plata guardada en la moneda
  // equivocada, sin ningún aviso. Ahora solo resetea si la cuenta destino cambió de verdad.
  it('elegir un método de pago NO pisa la moneda que el usuario ya eligió', async () => {
    vi.stubGlobal(
      'fetch',
      vi.fn((url: string, options?: RequestInit) => {
        if (options?.method === 'POST') {
          const body = JSON.parse(options.body as string);
          postCalls.push({ url, body });
          return jsonResponse(201, { ...editTx, ...body, id: 'tx-new', accountBalance: 1100 });
        }
        if (url.includes('/accounts')) return jsonResponse(200, [account, creditAccount]);
        if (url.includes('/payment-methods'))
          return jsonResponse(200, [
            { id: 'pm-1', accountId: 'acc-1', name: 'Débito', type: 'DEBIT', isDefault: false },
          ]);
        return jsonResponse(200, []);
      }),
    );

    renderCreateForm();

    await selectOption('Cuenta', 'acc-1', { exact: false });
    await selectOption('Moneda', '__other__', { exact: false });
    fireEvent.change(await screen.findByLabelText('Moneda (3 letras)', { exact: false }), {
      target: { value: 'usd' },
    });

    // el método NO cambia la cuenta destino → la moneda elegida tiene que sobrevivir
    await selectOption('Método de pago', 'pm-1', { exact: false });
    await waitFor(() =>
      expect(screen.getByLabelText('Moneda (3 letras)', { exact: false })).toHaveValue('USD'),
    );

    fireEvent.change(screen.getByLabelText(/Monto/), { target: { value: '250' } });
    fireEvent.click(screen.getByRole('button', { name: 'Guardar' }));

    await waitFor(() => expect(postCalls).toHaveLength(1));
    expect(postCalls[0].body).toMatchObject({ accountId: 'acc-1', currency: 'USD', amount: 250 });
  });

  it('"Otra…": permite cargar una moneda nueva (uppercase) y la manda', async () => {
    renderCreateForm();

    await selectOption('Cuenta', 'acc-1', { exact: false });
    await selectOption('Moneda', '__other__', { exact: false });
    fireEvent.change(await screen.findByLabelText('Moneda (3 letras)', { exact: false }), {
      target: { value: 'eur' },
    });
    fireEvent.change(screen.getByLabelText(/Monto/), { target: { value: '80' } });
    fireEvent.click(screen.getByRole('button', { name: 'Guardar' }));

    await waitFor(() => expect(postCalls).toHaveLength(1));
    expect(postCalls[0].body).toMatchObject({ accountId: 'acc-1', currency: 'EUR', amount: 80 });
  });
});

// Sprint 22.2: ruteo de tarjeta de crédito vinculada (D6/D7).
describe('TransactionForm ruteo de tarjeta (Sprint 22.2)', () => {
  const bankAcc = {
    id: 'bank-1', name: 'Banco', type: 'BANK', currency: 'ARS', balance: 5000, isInformal: false,
    statementCloseDay: null, paymentDueDay: null, balances: [{ currency: 'ARS', balance: 5000 }],
    createdAt: '2026-07-01T00:00:00', institution: null, linkedAccountId: null,
  };
  const linkedCard = {
    id: 'card-1', name: 'Visa *8190', type: 'CREDIT', currency: 'ARS', balance: -2000,
    isInformal: false, statementCloseDay: 10, paymentDueDay: 20,
    balances: [{ currency: 'ARS', balance: -2000 }], createdAt: '2026-07-01T00:00:00',
    institution: null, linkedAccountId: 'bank-1',
  };

  function renderCreate() {
    const queryClient = new QueryClient({
      defaultOptions: { queries: { retry: false }, mutations: { retry: false } },
    });
    render(
      <QueryClientProvider client={queryClient}>
        <AuthContext.Provider
          value={{ accessToken: 'test-token', status: 'authenticated', setAccessToken: () => {} }}
        >
          <ToastProvider>
            <TransactionForm onClose={vi.fn()} lockedType="EXPENSE" />
          </ToastProvider>
        </AuthContext.Provider>
      </QueryClientProvider>,
    );
  }

  it('la tarjeta vinculada no está en el selector de cuenta, sí en el de método, y rutea la tx', async () => {
    vi.stubGlobal(
      'fetch',
      vi.fn((url: string, options?: RequestInit) => {
        if (options?.method === 'POST') {
          const body = JSON.parse(options.body as string);
          postCalls.push({ url, body });
          return jsonResponse(201, { ...editTx, ...body, id: 'tx-new', accountBalance: -300 });
        }
        if (String(url).includes('/accounts')) return jsonResponse(200, [bankAcc, linkedCard]);
        return jsonResponse(200, []);
      }),
    );

    renderCreate();

    // abrir el selector de cuenta y esperar a que carguen
    const cuentaListbox = await openSelect('Cuenta', { exact: false });
    await within(cuentaListbox).findByRole('option', { name: /Banco/ });
    // la tarjeta vinculada NO es opción de cuenta (D7)
    expect(within(cuentaListbox).queryByRole('option', { name: /Visa \*8190 \(ARS\)/ })).not.toBeInTheDocument();
    // elegir la cuenta banco (dentro del listbox ya abierto)
    fireEvent.click(within(cuentaListbox).getByRole('option', { name: /Banco/ }));

    // …pero sí aparece en el selector de método (D6). Sprint 23: label "- Crédito".
    const metodoListbox = await openSelect('Método de pago', { exact: false });
    const cardOption = await within(metodoListbox).findByRole('option', { name: /Visa \*8190 - Crédito/ });
    expect(cardOption).toBeInTheDocument();
    fireEvent.click(cardOption);

    fireEvent.change(screen.getByLabelText(/Monto/), { target: { value: '300' } });
    fireEvent.click(screen.getByRole('button', { name: 'Guardar' }));

    await waitFor(() => expect(postCalls).toHaveLength(1));
    // la tx cae en la cuenta-tarjeta, sin método de pago
    expect(postCalls[0].body).toMatchObject({ accountId: 'card-1' });
    expect(postCalls[0].body.paymentMethodId).toBeUndefined();
  });

  // Sprint 27 — el flujo real de una compra en dólares con la tarjeta, que es el caso que el
  // sprint viene a habilitar: cuenta madre → la tarjeta como método → cambiar la moneda.
  // Hasta S27 la moneda quedaba clavada en ARS al elegir la tarjeta y no había forma de cargarla.
  it('ruteada a la tarjeta: la moneda arranca en la de la TARJETA y se puede cambiar a USD', async () => {
    vi.stubGlobal(
      'fetch',
      vi.fn((url: string, options?: RequestInit) => {
        if (options?.method === 'POST') {
          const body = JSON.parse(options.body as string);
          postCalls.push({ url, body });
          return jsonResponse(201, { ...editTx, ...body, id: 'tx-new', accountBalance: -100 });
        }
        // la madre es USD y la tarjeta ARS: si la moneda se arrastrara de la madre en vez de
        // reencuadrarse en la tarjeta, el default saldría mal y no se notaría
        if (String(url).includes('/accounts'))
          return jsonResponse(200, [{ ...bankAcc, currency: 'USD' }, linkedCard]);
        return jsonResponse(200, []);
      }),
    );

    renderCreate();

    await selectOption('Cuenta', 'bank-1', { exact: false });
    await selectOption('Método de pago', 'card:card-1', { exact: false });

    // default = la principal de la TARJETA (ARS), no la de la madre (USD)
    await waitFor(() => expect(selectValue('Moneda', { exact: false })).toBe('ARS'));

    // y ahora sí se puede pasar a dólares: la tarjeta todavía no tiene sub-balance USD, así
    // que el camino es "Otra…"
    await selectOption('Moneda', '__other__', { exact: false });
    fireEvent.change(await screen.findByLabelText('Moneda (3 letras)', { exact: false }), {
      target: { value: 'usd' },
    });
    fireEvent.change(screen.getByLabelText(/Monto/), { target: { value: '100' } });
    fireEvent.click(screen.getByRole('button', { name: 'Guardar' }));

    await waitFor(() => expect(postCalls).toHaveLength(1));
    expect(postCalls[0].body).toMatchObject({ accountId: 'card-1', currency: 'USD', amount: 100 });
  });
});
