import { afterEach, describe, expect, it, vi } from 'vitest';
import { fireEvent, render, screen, within } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { MemoryRouter } from 'react-router-dom';
import { AuthContext } from '../auth/context';
import { ToastProvider } from '../../components/ui/ToastProvider';
import { TransactionsPage } from './TransactionsPage';
import { jsonResponse } from '../../test/mockResponse';

// Presentación de las filas del feed (tanda de UI post-S29): lápiz en vez de "Editar", ⓘ del
// gasto compartido pegada a la descripción, "Borrar" fuera de la fila, y las transferencias en
// dos renglones.

const account = { id: 'acc-1', name: 'Mercado Pago', type: 'WALLET', currency: 'ARS', balance: 1000 };
const account2 = { id: 'acc-2', name: 'Banco Nación', type: 'BANK', currency: 'ARS', balance: 5000 };

const baseTx = {
  accountId: 'acc-1',
  categoryId: null,
  paymentMethodId: null,
  type: 'EXPENSE' as const,
  currency: 'ARS',
  exchangeRateAtTime: null,
  createdAt: '2026-07-01T00:00:00',
  recurringExpenseId: null,
  autoGenerated: false,
  settledShareId: null,
  settledExpenseId: null,
  settledExpenseDescription: null,
};

const plainTx = {
  ...baseTx,
  id: 'tx-plain',
  amount: 5000,
  date: '2026-07-02',
  description: 'Café',
  sharedAmount: 0,
  shareCount: 0,
  pendingCount: 0,
};

const sharedTx = {
  ...baseTx,
  id: 'tx-shared',
  amount: 30000,
  date: '2026-07-01',
  description: 'Cena parrilla',
  sharedAmount: 20000,
  shareCount: 2,
  pendingCount: 2,
};

// Intra-cuenta: misma cuenta, cambio de moneda. Es la fila que antes ocupaba una línea larga.
const intraTransfer = {
  id: 'tr-intra',
  fromAccountId: 'acc-1',
  toAccountId: 'acc-1',
  fromAmount: 1000,
  toAmount: 1,
  fromCurrency: 'ARS',
  toCurrency: 'USD',
  date: '2026-06-30',
  description: 'Compra de dólares',
  createdAt: '2026-06-30T00:00:00',
};

function stubFetch(txContent: unknown[], transfers: unknown[] = []) {
  vi.stubGlobal(
    'fetch',
    vi.fn((url: string) => {
      if (url.includes('/transfers'))
        return jsonResponse(200, {
          content: transfers,
          page: 0,
          size: 100,
          totalElements: transfers.length,
          totalPages: 1,
        });
      if (url.includes('/transactions'))
        return jsonResponse(200, {
          content: txContent,
          page: 0,
          size: 20,
          totalElements: txContent.length,
          totalPages: 1,
        });
      if (url.includes('/accounts')) return jsonResponse(200, [account, account2]);
      return jsonResponse(200, []);
    }),
  );
}

afterEach(() => vi.unstubAllGlobals());

// Variante DESKTOP de la tabla: useIsDesktop decide qué celdas se montan y en jsdom no hay
// matchMedia (default mobile). Este stub simula md+ para los tests que miran las columnas
// Tipo/Categoría/Cuenta; sin stub, la fila se testea en su variante mobile (sub-línea).
function stubDesktop() {
  vi.stubGlobal('matchMedia', () => ({
    matches: true,
    addEventListener: () => {},
    removeEventListener: () => {},
  }));
}

function renderPage() {
  const queryClient = new QueryClient({ defaultOptions: { queries: { retry: false } } });
  render(
    <QueryClientProvider client={queryClient}>
      <AuthContext.Provider
        value={{ accessToken: 't', status: 'authenticated', setAccessToken: () => {} }}
      >
        <ToastProvider>
          <MemoryRouter>
            <TransactionsPage />
          </MemoryRouter>
        </ToastProvider>
      </AuthContext.Provider>
    </QueryClientProvider>,
  );
}

describe('TransactionsPage — presentación de las filas', () => {
  it('la acción de la fila es un lápiz accesible, y "Borrar" ya no está ahí', async () => {
    stubFetch([plainTx]);
    renderPage();

    const pencil = await screen.findByRole('button', { name: 'Editar movimiento' });
    expect(pencil).toBeInTheDocument();
    expect(pencil.tagName).toBe('BUTTON');
    // El texto "Editar" desapareció de la fila; sólo queda el ícono.
    expect(screen.queryByRole('button', { name: 'Editar' })).not.toBeInTheDocument();
    expect(screen.queryByRole('button', { name: 'Borrar' })).not.toBeInTheDocument();
  });

  it('al abrir la edición lleva la vista al form', async () => {
    // jsdom no implementa scrollIntoView; se stubea para poder afirmar que se llamó.
    const scrollIntoView = vi.fn();
    const original = Element.prototype.scrollIntoView;
    Element.prototype.scrollIntoView = scrollIntoView;

    try {
      stubFetch([plainTx]);
      renderPage();

      expect(scrollIntoView).not.toHaveBeenCalled();
      fireEvent.click(await screen.findByRole('button', { name: 'Editar movimiento' }));
      await screen.findByRole('form', { name: 'Editar transacción' });

      // Sin esto se puede estar al fondo de la tabla editando algo que no se ve.
      expect(scrollIntoView).toHaveBeenCalled();
    } finally {
      Element.prototype.scrollIntoView = original;
    }
  });

  it('"Borrar" aparece recién al abrir la edición', async () => {
    stubFetch([plainTx]);
    renderPage();

    fireEvent.click(await screen.findByRole('button', { name: 'Editar movimiento' }));

    const form = await screen.findByRole('form', { name: 'Editar transacción' });
    expect(within(form).getByRole('button', { name: 'Borrar' })).toBeInTheDocument();
  });

  it('la ⓘ del gasto compartido está sólo en las filas compartidas y abre el detalle', async () => {
    stubFetch([sharedTx, plainTx]);
    renderPage();

    const info = await screen.findAllByRole('button', {
      name: 'Ver detalle del gasto compartido',
    });
    // Dos filas en la tabla, una sola compartida.
    expect(info).toHaveLength(1);

    fireEvent.click(info[0]);
    expect(await screen.findByRole('dialog')).toBeInTheDocument();
  });

  it('la fila compartida muestra el total y tu parte por separado', async () => {
    stubFetch([sharedTx]);
    renderPage();

    // Por title y no por texto: el tooltip de la ⓘ también nombra el gasto.
    expect(await screen.findByTitle('Cena parrilla')).toBeInTheDocument();
    expect(screen.getByText(/\(2 restantes\)/)).toBeInTheDocument();
    expect(screen.getByText(/Te corresponde/)).toBeInTheDocument();
  });

  it('la ⓘ del cobro explica de qué gasto vino y abre ese reparto', async () => {
    const settlement = {
      ...baseTx,
      id: 'tx-cobro',
      type: 'INCOME' as const,
      amount: 10000,
      date: '2026-07-05',
      description: 'Cobro de Juan — Cena parrilla',
      sharedAmount: 0,
      shareCount: 0,
      pendingCount: 0,
      settledShareId: 'share-1',
      settledExpenseId: 'tx-shared',
      settledExpenseDescription: 'Cena parrilla',
    };
    stubFetch([settlement]);
    renderPage();

    const info = await screen.findByRole('button', {
      name: 'Ver el gasto compartido que originó este cobro',
    });
    // El tooltip nombra el gasto: "Cobro" solo no dice de qué.
    expect(screen.getByRole('tooltip')).toHaveTextContent('«Cena parrilla»');

    fireEvent.click(info);
    expect(await screen.findByRole('dialog')).toBeInTheDocument();
  });

  it('la transferencia intra-cuenta parte el nombre y el par de monedas en dos renglones', async () => {
    stubDesktop();
    stubFetch([], [intraTransfer]);
    renderPage();

    // Se consulta DENTRO de la fila: "Mercado Pago" también aparece en los chips de cuenta y en
    // el select del filtro.
    const row = (await screen.findByText('Compra de dólares')).closest('tr')!;
    // Antes era una sola línea "Mercado Pago · ARS → USD"; ahora son dos nodos separados.
    expect(within(row).getByText('Mercado Pago')).toBeInTheDocument();
    expect(within(row).getByText('ARS → USD')).toBeInTheDocument();
    expect(within(row).queryByText(/Mercado Pago · ARS/)).not.toBeInTheDocument();
  });

  it('en mobile la fila de transferencia lleva el recorrido en la sub-línea', async () => {
    // SIN stubDesktop: jsdom = variante mobile. La columna Cuenta no se monta y el recorrido
    // (cuenta · monedas) baja a un renglón bajo la descripción.
    stubFetch([], [intraTransfer]);
    renderPage();

    const row = (await screen.findByText('Compra de dólares')).closest('tr')!;
    expect(within(row).getByText('Mercado Pago · ARS → USD')).toBeInTheDocument();
  });

  it('el tipo "Entre cuentas" va en dos renglones', async () => {
    stubDesktop();
    stubFetch([], [intraTransfer]);
    renderPage();

    const row = (await screen.findByText('Compra de dólares')).closest('tr')!;
    // El <br/> deja el texto partido: el nodo de la celda contiene ambas palabras.
    expect(row.textContent).toContain('Entre');
    expect(row.textContent).toContain('cuentas');
  });
});
