import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { render, screen } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { MemoryRouter } from 'react-router-dom';
import { AuthContext } from '../auth/context';
import { TransactionsPage } from './TransactionsPage';
import { ToastProvider } from '../../components/ui/ToastProvider';
import { jsonResponse } from '../../test/mockResponse';

// S39 §6.1 — deep-link del centro de notificaciones a la bandeja. El tap en "Vaqui cargó
// resumen-visa.pdf" cae en /transactions?review=1 y tiene que abrir la tab "Por revisar".
//
// El caso interesante es el de abajo: si mientras tanto ya revisaste todo, la tab NO existe.
// Abrirla igual dejaría la página en blanco, así que cae al feed sin decir nada: no hay nada
// que revisar es una buena noticia, no un error.

const emptyPage = { content: [], page: 0, size: 20, totalElements: 0, totalPages: 0 };

const accounts = [
  { id: 'a1', name: 'Efectivo', type: 'CASH', currency: 'ARS', balance: 1500, isInformal: false,
    statementCloseDay: null, paymentDueDay: null, balances: [{ currency: 'ARS', balance: 1500 }],
    createdAt: '2026-07-01T00:00:00', institution: null, linkedAccountId: null },
];

const categories = [
  { id: 'c2', userId: null, name: 'Comida', type: 'EXPENSE', color: null, icon: null,
    sourceDefaultCategoryId: null, createdAt: '2026-07-01T00:00:00' },
];

const pendiente = {
  id: 'tx-1',
  accountId: 'a1',
  categoryId: null,
  paymentMethodId: null,
  type: 'EXPENSE',
  amount: 45000,
  currency: 'ARS',
  exchangeRateAtTime: null,
  date: '2026-06-05',
  description: 'Pago con QR Super',
  createdAt: '2026-08-04T10:00:00',
  recurringExpenseId: null,
  autoGenerated: false,
  sharedAmount: 0,
  settledShareId: null,
  transferId: null,
  settledCount: 0,
  origin: 'TELEGRAM_IMPORT',
  pendingReview: true,
};

function mockFetch(pendingCount: number) {
  vi.stubGlobal(
    'fetch',
    vi.fn((url: string) => {
      if (url.includes('/transfers')) return jsonResponse(200, emptyPage);
      if (url.includes('pendingReview=true')) {
        return jsonResponse(200, pendingCount === 0
          ? emptyPage
          : { content: [pendiente], page: 0, size: 100, totalElements: pendingCount, totalPages: 1 });
      }
      if (url.includes('/transactions')) return jsonResponse(200, emptyPage);
      if (url.includes('/categories')) return jsonResponse(200, categories);
      if (url.includes('/accounts')) return jsonResponse(200, accounts);
      return jsonResponse(200, []);
    }),
  );
}

afterEach(() => vi.unstubAllGlobals());

function renderPage(url: string) {
  const queryClient = new QueryClient({ defaultOptions: { queries: { retry: false } } });
  render(
    <QueryClientProvider client={queryClient}>
      <AuthContext.Provider
        value={{ accessToken: 'test-token', status: 'authenticated', setAccessToken: () => {} }}
      >
        <ToastProvider>
          <MemoryRouter initialEntries={[url]}>
            <TransactionsPage />
          </MemoryRouter>
        </ToastProvider>
      </AuthContext.Provider>
    </QueryClientProvider>,
  );
}

describe('TransactionsPage — deep-link ?review=1 (S39)', () => {
  beforeEach(() => mockFetch(1));

  it('abre la bandeja con lo que entró solo', async () => {
    renderPage('/transactions?review=1');

    expect(await screen.findByRole('button', { name: 'Por revisar (1)' }))
      .toHaveAttribute('aria-current', 'page');
    // La descripción se edita en la planilla, así que es el value de un input.
    expect(await screen.findByDisplayValue('Pago con QR Super')).toBeInTheDocument();
    // S39: la bandeja dice quién lo trajo.
    expect(await screen.findByText('lo leyó Vaqui')).toBeInTheDocument();
  });

  it('sin el param arranca en el feed aunque haya pendientes', async () => {
    renderPage('/transactions');

    expect(await screen.findByRole('button', { name: 'Movimientos' }))
      .toHaveAttribute('aria-current', 'page');
  });
});

describe('TransactionsPage — ?review=1 sin nada pendiente (S39 §8.9)', () => {
  beforeEach(() => mockFetch(0));

  it('cae al feed sin romperse y sin avisar nada', async () => {
    renderPage('/transactions?review=1');

    expect(await screen.findByRole('button', { name: 'Nuevo movimiento' })).toBeInTheDocument();
    // La tab no se renderiza con cero pendientes.
    expect(screen.queryByRole('button', { name: /Por revisar/ })).toBeNull();
    expect(screen.queryByRole('alert')).toBeNull();
  });
});
